apiVersion: apps/v1
kind: Deployment
metadata:
  name: falling-leaves
spec:
  replicas: 2
  selector:
    matchLabels:
      app: falling-leaves
  template:
    metadata:
      labels:
        app: falling-leaves
    spec:
      containers:
      - name: falling-leaves
        image: sasha444/falling-leaves-v1:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: falling-leaves
spec:
  type: NodePort
  selector:
    app: falling-leaves
  ports:
  - port: 80
    targetPort: 80
